# Generated by Django 5.2.15 on 2026-08-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_projectcustomsettings_auto_conventional_commit_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'Github'), ('gitlab', 'GitLab'), ('oidc-free', 'OIDC')]),
        ),
    ]
