# Generated by Django 5.2.15 on 2026-08-31 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0129_projectcustomsettings_auto_conventional_commit_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalUnit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Organizational Unit Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, verbose_name="Organizational Unit Slug"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("logo_props", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_units",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit",
                "verbose_name_plural": "Organizational Units",
                "db_table": "organizational_units",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationalUnitMembership",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("lead", "Lead"), ("member", "Member")],
                        default="member",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="db.organizationalunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_unit_memberships",
                        to="db.workspace",
                    ),
                ),
                (
                    "workspace_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_unit_memberships",
                        to="db.workspacemember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit Membership",
                "verbose_name_plural": "Organizational Unit Memberships",
                "db_table": "organizational_unit_memberships",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationalUnitProject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "default_role",
                    models.PositiveSmallIntegerField(
                        choices=[(20, "Admin"), (15, "Member"), (5, "Guest")],
                        default=15,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_projects",
                        to="db.organizationalunit",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_unit_links",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_unit_projects",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit Project",
                "verbose_name_plural": "Organizational Unit Projects",
                "db_table": "organizational_unit_projects",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationalUnitGrant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "granted_role",
                    models.PositiveSmallIntegerField(
                        choices=[(20, "Admin"), (15, "Member"), (5, "Guest")]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "organizational_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="db.organizationalunit",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_unit_grants",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_unit_grants",
                        to="db.workspace",
                    ),
                ),
                (
                    "workspace_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_unit_grants",
                        to="db.workspacemember",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="db.organizationalunitmembership",
                    ),
                ),
                (
                    "unit_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="db.organizationalunitproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Unit Grant",
                "verbose_name_plural": "Organizational Unit Grants",
                "db_table": "organizational_unit_grants",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationalProjectAccessState",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "baseline_role",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(20, "Admin"), (15, "Member"), (5, "Guest")],
                        null=True,
                    ),
                ),
                (
                    "last_applied_role",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(20, "Admin"), (15, "Member"), (5, "Guest")],
                        null=True,
                    ),
                ),
                ("created_by_org_layer", models.BooleanField(default=False)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_access_states",
                        to="db.project",
                    ),
                ),
                (
                    "project_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizational_access_states",
                        to="db.projectmember",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_access_states",
                        to="db.workspace",
                    ),
                ),
                (
                    "workspace_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_access_states",
                        to="db.workspacemember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Project Access State",
                "verbose_name_plural": "Organizational Project Access States",
                "db_table": "organizational_project_access_states",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("workspace_member", "project"),
                        name="org_access_state_unique_member_project_when_deleted_at_null",
                    )
                ],
                "unique_together": {("workspace_member", "project", "deleted_at")},
            },
        ),
        migrations.AddConstraint(
            model_name="organizationalunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("workspace", "slug"),
                name="org_unit_unique_workspace_slug_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationalunit",
            unique_together={("workspace", "slug", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="organizationalunitmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organizational_unit", "workspace_member"),
                name="org_unit_membership_unique_unit_member_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationalunitmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("is_active", True), ("role", "lead")
                ),
                fields=("organizational_unit",),
                name="org_unit_membership_single_active_lead_per_unit",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationalunitmembership",
            unique_together={("organizational_unit", "workspace_member", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="organizationalunitproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("organizational_unit", "project"),
                name="org_unit_project_unique_unit_project_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationalunitproject",
            unique_together={("organizational_unit", "project", "deleted_at")},
        ),
        migrations.AddConstraint(
            model_name="organizationalunitgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("membership", "unit_project"),
                name="org_unit_grant_unique_membership_unit_project_when_deleted_at_null",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationalunitgrant",
            unique_together={("membership", "unit_project", "deleted_at")},
        ),
    ]
