# Generated by Django 5.2.15 on 2026-09-01 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Drop the table-wide unique index on ``issue_id``.

    ``IssueOrganizationalUnit.issue`` shipped in 0131 as a OneToOneField, which
    is a ForeignKey(unique=True): the index it creates covers soft-deleted rows
    too. Because clearing a work item's responsible unit is a soft delete, the
    sequence set -> clear -> set failed on a unique violation against the row
    the user had just cleared. Turning the field into a plain ForeignKey leaves
    the partial constraint from 0131
    (``issue_org_unit_unique_issue_when_deleted_at_null``) as the only rule:
    one live link per work item, cleared ones kept as history.

    Forward-only in effect on existing data — no rows change, only the index is
    dropped — so this is safe to apply to a database already carrying links.
    """

    dependencies = [
        ("db", "0131_issue_organizational_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueorganizationalunit",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizational_unit_links",
                to="db.issue",
            ),
        ),
    ]
